completion
jwilk/ubanner pull request #1
Opened 2024-01-02 15:23 UTC by crpb

zsh completion

2024-01-03 19:46 UTC, jwilk commented
I have no idea how to test this.

2024-01-22 16:17 UTC, crpb commented
maybe there is an easier way but well.. 
```
sudo apt-get install zsh
sudo useradd -m -s /bin/zsh test
sudo -i -u test
# hit "2" (auto populate defaults)
git clone --branch completion https://github.com/crpb/ubanner
chmod +x ubanner/ubanner
sed -i '2i PATH="$HOME/ubanner:$PATH"\nfpath=($fpath ~/ubanner/completion)' ~/.zshrc
source ~/.zshrc
ubanner <TABTABTAB>
```
or something alike o_0
```

                    ░░▒███████████████▒░░                                       ░▒▒███████████████▒▒░                                          ░░▒██████████████▒░░
                 ░▒███████████████████████▒                                  ░▒████████████████████████▒                                     ▒███████████████████████░
               ░████████████████████████████▒                               █████████████████████████████▒                                 ▒███████████████████████████░
          ▒██▒▒███████████████████████████████                            ░████████████████████████████████                               ██████▒██████████▒▒▒██████████░
       ░██▒ ░█▒▒██░      ░▒███████▒       ▒█████▒██░                     ░████▒░    ░▒██████████░     ░█████                             ▒███▒░▒███▒░  ▒████▒░  ░▒███████
      ▒█▒ ░██  ▒█░         ░████▒          ██  ▒░ ░██░             ░░▒▒░░████          ▒██████░         ░███▒░░▒▒░                 ▒███████████▒░   ░▒████▒░▒██▒    ░█████████▒░
     ██░ ▒░█  ░█▒   ░░░░     ██▒     ░░░   ░█▒  ▒█▒ ░██          ▒██▒░▒█████             ████            ▒█████░▒███             ▒█▒░  ▒█████░    ░█▒░  ▒██▒░  ░▒      ▒███   ▒██
    ██    ░   ██  ▒█▒████░    ░    ██▒████  ▒█░  ▒ ░  ██░       ██▒    ▒███▒  ░▒████▒     █▒    ░█████▒   ████    ░██░          ▒█▒     ███░      ░ ░▒▒█▒░▒████░         ▒█     ██
   ██        ▒██  ████████        ░███████▒  ██        ██      ▒█▒      ███▒  █▒▒█████         ░█▒▒█████  ███░      ██░         ██     ▒█░       ░▒██▒▒▒███░░  ░▒▒        ░█▒   ░█▒
   ██       ░███  ████░ ░░        ░████  █░ ░██▒       ▒█▒     ██       ████ ░█████▒▒█         ▒█████▒▒█  ███       ░█▒         ██   ░█▒             ░▒▒█░ ░▒██▒░           ▒█░ ░██
   ██       ▒███▒  ▒██▒▒░  ░░░▒░░   ▒▒▒░▒░  ████       ░█▒     ██       ████  ▒███  ▒▒          ████ ░█░ ▒███        ██         ██  ▒█░          ░▒▒████▒██▒▒░ ░▒█▒          ░██▒█▒
   ░█▒       █████      ░▒▒░░░░░░░▒▒      ░█████       ██░     ██       █████   ░░░░  ░▒▒███▒▒▒░ ░░░░░  ░████       ░█▒         ▒████          ▒█▒ ░░       ░▒▒   ▒█▒          ███
    ░██      ▒██░        ░▒      ░▒░        ███░      ▒█░      ▒█▒      █████▒  ░░ ▒███▒      ░████ ░░ ░█████       ██░          ███         ░██   ░██      ██▒    ░██░         ██░
     ░██░     ▒█▒       ▒█▒       ██░       ██▒      ██░        ██▒     ████   ▒█▒███ ░██    ▒█▒ ▒██▒██  ▒███     ░██░           ██         ▒█▒    ░░        ░▒      ▒█░        ░██
      ░██░     ██▒                         ▒█▒     ░██░          ▒██▒░░▒███    ░█▒ ░████▒█▒░█▒  ▒█▒ ░█▒   ███▒░░░███░           ██░        ▒█▒                        ▒█░        ██▒
       ▒██      ██                        ░██     ░██░             ░▒▒▒████  ░████▒ ▒█░ ░███   ▒█░ ░█████ █████▒▒▒░            ▒█▒        ░█▒                          ██        ░██
       ███      ██░          ░▒▒          ▒█▒     ░██                  ▒███░ ██░░▒███░ ░██░   ██  ▒█▒░ ██ ████                 ██         ██░          ▒███           ███▒        ▒█▒
      ░██░      ██         ░████▒         ▒█░      ██▒                 ░████  ▒█░▒██░ ░█▒    █▒ ░█▒  ░██ ▒███▒                ▒█▒        ▒███░        █████         ░█████         ██
      ███       ██▒        █████          ██▒      ░██                  █████  ███▒   ░        ▒█░  ███ ░████                 ██         ██████░      ▒██▒         ▒██████▒        ██▒
     ░██       █████░     ░░▒▒░         ▒████       ▒██                  ████████░                ░██▒██████░                ▒██        ░██▒█████▒░  ▒▒▒▒       ░█████▒ ░██        ░██
     ██░      ░███████▒░  ░▒▒▒░      ░▒██████▒       ██░                  █████░                 ▒█▒   ▒███░                 ███        ██░  ▒███████▒▒░░░░▒▒███████░    ██░       ░██░
    ███       ██  ▒████████▒▒▒▒▒▒▒██████▒░  ██░      ░██                 ░███░                 ▒██░      ▒██░                ███        ██     ░▒███████████████▒░       ▒█▒       ░██░
   ░██       ██░    ░▒███████████████▒░     ░██       ███              ▒███░                 ▒██▒          ▒██▒              ██▒       ▒██          ░▒▒▒▒▒▒▒░░           ░██       ░██░
   ▒▒░      ░▒▒          ░░▒▒▒▒▒▒░░          ▒▒▒       ▒▒           ░███▒░                ▒███▒              ▒███░           ▒▒░       ▒▒░                                ▒▒       ░▒▒
                                                                 ░▒███░               ░▒██████▒░               ░███▒░
                                                               ░▒▒▒░                ░▒▒▒░    ░▒▒▒░                ░▒▒▒░

```

2024-02-05 13:33 UTC, jwilk commented
I've simpified zsh test setup to this:
```shell
tmpdir=$(mktemp -d)
cat > "$tmpdir/.zshrc" <<EOF
path+=(/path/to/ubanner)
fpath+=(/path/to/ubanner/completion)
autoload -Uz compinit
compinit
EOF
ZDOTDIR=$tmpdir zsh
```

2024-03-01 10:04 UTC, jwilk requested changes

2024-03-01 10:04 UTC, jwilk commented on completion/_ubanner
> +  {-s,--font-size}'[font size in pixels (default: 28)]:size:(28 36 42 50 58 64 72 80 88 96)' \
That's a weird list of integers. Sometimes the distance between them is 6, sometimes 8, with no apparent pattern.
Anyway: typing 64 is easier than 6[tab], so just get rid of the list?

2024-03-01 10:04 UTC, jwilk commented on completion/_ubanner
> +  {-S,--full-screen}'[full screen mode]'
Please steal the description from the help message.

2024-03-06 17:18 UTC, jwilk requested changes

2024-03-06 17:18 UTC, jwilk commented on completion/_ubanner
The directory name should indicate that is for zsh. Maybe `completion/zsh/` or `zshcompletion/`?

2024-03-06 17:18 UTC, jwilk commented on completion/_ubanner
Please add copyright statement and a license info.
For example, in `Makefile` it looks like this:
https://github.com/jwilk/ubanner/blob/5602b78d98289ca1576cd4019976ab751738f162/Makefile#L1-L2

2024-03-16 08:21 UTC, crpb commented on completion/_ubanner
> +  {-s,--font-size}'[font size in pixels (default: 28)]:size:(28 36 42 50 58 64 72 80 88 96)' \
> Anyway: typing 64 is easier than 6[tab], so just get rid of the list?
that is actually there so you can complete them like this
```
% ubanner --font-size
completing size
28  36  42  50  58  64  72  80  88  96
```
i just started with a number and kept going ^_^

2024-03-16 08:31 UTC, crpb commented on completion/_ubanner
i guess `completion/$shell` make the most sence.
but if it's only zsh and bash than they can be discerned by the leading underscore fore zsh :stuck_out_tongue_winking_eye:

2024-03-16 08:55 UTC, crpb commented on completion/_ubanner
i don't think i ever saw a completion file with a license statement :astonished: and now after searching its only a [few](https://github.com/search?q=repo%3Azsh-users%2Fzsh++path%3ACompletion++%2F%5E%23.*%5C+mit%2F+OR+%2F%5E%23.*gnu%2F+OR+%2F%5E%23.*license%2F+&type=code) if that 'search' was working...
when you look at the big [picture](https://github.com/search?q=repo%3Azsh-users%2Fzsh++path%3ACompletion+&type=code) it seems nobody cares :heart_eyes_cat:

2024-03-25 11:37 UTC, jwilk commented on completion/zsh
> +  '(-f --font)'{-f,--font}'[use this fontface]:font:->fonts'
```suggestion
  '(-f --font)'{-f,--font}'[use this font face]:font:->fonts'
```

2024-03-25 11:37 UTC, jwilk commented on completion/zsh
> +# # SPDX-License-Identifier: MIT
```suggestion

# Copyright © 2024 Christopher Bock <christopher@bocki.com>
# SPDX-License-Identifier: MIT

```

2024-03-25 13:57 UTC, jwilk commented on completion/_ubanner
Now there's no underscore, so I can't test it without jumping through an extra hop.
Can you make it `completion/zsh/_ubanner`?

2024-03-25 13:57 UTC, jwilk commented on completion/zsh
> +  '(-s --font-size)'{-s,--font-size}'[font size in pixels]: :_numbers -d28 -l14 -m280'
What are the `_numbers` options for? They don't seem to have any effect. In particular, I'm not being shown what's the default for `--font-size`. :confused:

```console
% ubanner -⭾
…
--font-size    -s  -- font size in pixels                                     
…
```

2024-03-25 13:57 UTC, jwilk commented on completion/zsh
> +  '--list-fonts:[print list of available font faces]'
I'm not being shown descriptions for these options. :confused:
```console
% ubanner -⭾
…          
--help             --list-fonts       --version          -h
```

2024-03-25 21:28 UTC, jwilk commented on completion/zsh
> +  '--list-fonts:[print list of available font faces]'
```suggestion
  + '(excl)'
  {-h,--help}'[show help]'
  '--version[show version information and exit]'
  '--list-fonts[print list of available font faces]'
```

2024-04-01 14:00 UTC, crpb commented on completion/zsh
> +  '(-s --font-size)'{-s,--font-size}'[font size in pixels]: :_numbers -d28 -l14 -m280'
Now after using
```
zstyle ':completion:*' menu select=1
zstyle ':completion:*' completer _complete
zstyle ':completion:*:descriptions'    format $'%{\e[0;31m%}completing %B%d%b%{\e[0m%}'
zstyle ':completion:*:messages'        format '%d'
zstyle ':completion:*:options'         auto-description '%d'
```
it should be clear?

2024-04-04 18:03 UTC, crpb reviewed
🦆🐔🪱

2024-04-06 13:43 UTC, merged